// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: ESP32S3_UI

#include "../ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Home, &ui_img_1486146667, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_header = lv_obj_create(ui_Home);
lv_obj_set_width( ui_header, 320);
lv_obj_set_height( ui_header, 30);
lv_obj_set_align( ui_header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_header, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_header, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_header, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_header, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WIFILabel = lv_label_create(ui_Home);
lv_obj_set_width( ui_WIFILabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WIFILabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WIFILabel, 7 );
lv_obj_set_y( ui_WIFILabel, -225 );
lv_obj_set_align( ui_WIFILabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_WIFILabel,"Wifi连接");
lv_obj_set_style_text_color(ui_WIFILabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WIFILabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WIFILabel, &ui_font_MiSansN14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WIFISymbel = lv_label_create(ui_Home);
lv_obj_set_width( ui_WIFISymbel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WIFISymbel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WIFISymbel, -90 );
lv_obj_set_y( ui_WIFISymbel, -225 );
lv_obj_set_align( ui_WIFISymbel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WIFISymbel,"");
lv_obj_set_style_text_color(ui_WIFISymbel, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WIFISymbel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WIFISymbel, &ui_font_symbolsalibaba16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaderTimeHome = lv_label_create(ui_Home);
lv_obj_set_width( ui_HeaderTimeHome, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaderTimeHome, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeaderTimeHome, 0 );
lv_obj_set_y( ui_HeaderTimeHome, -225 );
lv_obj_set_align( ui_HeaderTimeHome, LV_ALIGN_CENTER );
lv_label_set_text(ui_HeaderTimeHome,"12:12");
lv_obj_set_style_text_color(ui_HeaderTimeHome, lv_color_hex(0xFCF6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeaderTimeHome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeaderTimeHome, &ui_font_MiSansM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SliderHeaderBat = lv_slider_create(ui_Home);
lv_slider_set_value( ui_SliderHeaderBat, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderHeaderBat)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderHeaderBat, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderHeaderBat, 30);
lv_obj_set_height( ui_SliderHeaderBat, 15);
lv_obj_set_x( ui_SliderHeaderBat, 124 );
lv_obj_set_y( ui_SliderHeaderBat, -225 );
lv_obj_set_align( ui_SliderHeaderBat, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SliderHeaderBat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderHeaderBat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderHeaderBat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SliderHeaderBat, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderHeaderBat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderHeaderBat, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SliderHeaderBat, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderHeaderBat, lv_color_hex(0x05F850), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderHeaderBat, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_SliderHeaderBat, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SliderHeaderBat, lv_color_hex(0xFCFAFA), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SliderHeaderBat, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SliderHeaderBat, 1, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SliderHeaderBat, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderHeaderBat, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderHeaderBat, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PanelBathead = lv_obj_create(ui_Home);
lv_obj_set_width( ui_PanelBathead, 5);
lv_obj_set_height( ui_PanelBathead, 8);
lv_obj_set_x( ui_PanelBathead, 141 );
lv_obj_set_y( ui_PanelBathead, -225 );
lv_obj_set_align( ui_PanelBathead, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelBathead, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelBathead, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelBathead, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelBathead, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelBathead, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHeaderBatValue = lv_label_create(ui_Home);
lv_obj_set_width( ui_LabelHeaderBatValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHeaderBatValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHeaderBatValue, 83 );
lv_obj_set_y( ui_LabelHeaderBatValue, -225 );
lv_obj_set_align( ui_LabelHeaderBatValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHeaderBatValue,"50%");
lv_obj_set_style_text_color(ui_LabelHeaderBatValue, lv_color_hex(0xFAF7F7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHeaderBatValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHeaderBatValue, &ui_font_MiSansM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Body = lv_obj_create(ui_Home);
lv_obj_set_width( ui_Body, 320);
lv_obj_set_height( ui_Body, 360);
lv_obj_set_x( ui_Body, 0 );
lv_obj_set_y( ui_Body, -30 );
lv_obj_set_align( ui_Body, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Body, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_set_scrollbar_mode(ui_Body, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_Body, LV_DIR_HOR);
lv_obj_set_style_radius(ui_Body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Body, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Body, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_home1 = lv_obj_create(ui_Body);
lv_obj_set_width( ui_home1, 320);
lv_obj_set_height( ui_home1, 360);
lv_obj_set_x( ui_home1, 321 );
lv_obj_set_y( ui_home1, 6 );
lv_obj_set_align( ui_home1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_home1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_home1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ToolIcon = lv_img_create(ui_home1);
lv_img_set_src(ui_ToolIcon, &ui_img_358101685);
lv_obj_set_width( ui_ToolIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ToolIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ToolIcon, -110 );
lv_obj_set_y( ui_ToolIcon, -130 );
lv_obj_set_align( ui_ToolIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ToolIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ToolIcon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_home2 = lv_obj_create(ui_Body);
lv_obj_set_width( ui_home2, 300);
lv_obj_set_height( ui_home2, 300);
lv_obj_set_x( ui_home2, -1 );
lv_obj_set_y( ui_home2, -12 );
lv_obj_set_align( ui_home2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_home2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_home2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_home2, lv_color_hex(0x221E1E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home2, 230, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_home2, lv_color_hex(0xEDEAEA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_home2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_home2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_home2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 2 );
lv_obj_set_y( ui_Label1, -96 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"12:30");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_MiSansB40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ToolIcon, ui_event_ToolIcon, LV_EVENT_ALL, NULL);

}
