// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: ESP32S3_UI

#include "../ui.h"

void ui_settings_screen_init(void)
{
ui_settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingHeader = lv_obj_create(ui_settings);
lv_obj_set_width( ui_settingHeader, 320);
lv_obj_set_height( ui_settingHeader, 50);
lv_obj_set_align( ui_settingHeader, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_settingHeader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_settingHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_settingHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeImg = lv_img_create(ui_settingHeader);
lv_img_set_src(ui_HomeImg, &ui_img_316889752);
lv_obj_set_width( ui_HomeImg, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_HomeImg, LV_SIZE_CONTENT);   /// 40
lv_obj_set_align( ui_HomeImg, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_HomeImg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HomeImg, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_settingHeader);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label11,"设置");
lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x040000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &ui_font_MiSansM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StepPannel = lv_obj_create(ui_settings);
lv_obj_set_width( ui_StepPannel, 320);
lv_obj_set_height( ui_StepPannel, 430);
lv_obj_set_x( ui_StepPannel, 0 );
lv_obj_set_y( ui_StepPannel, 30 );
lv_obj_set_align( ui_StepPannel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_StepPannel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_StepPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_StepPannel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StepPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StepPannel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StepPannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_StepPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_StepPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_StepPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_StepPannel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_StepPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bat = lv_obj_create(ui_StepPannel);
lv_obj_set_width( ui_Bat, 320);
lv_obj_set_height( ui_Bat, 40);
lv_obj_set_align( ui_Bat, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Bat, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Bat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bat, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Bat, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Bat, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dianchi = lv_label_create(ui_Bat);
lv_obj_set_width( ui_dianchi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dianchi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dianchi, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_dianchi,"电池");
lv_obj_set_style_text_font(ui_dianchi, &ui_font_MiSansM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dayu = lv_label_create(ui_Bat);
lv_obj_set_width( ui_dayu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dayu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dayu, 0 );
lv_obj_set_y( ui_dayu, 3 );
lv_obj_set_align( ui_dayu, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_dayu,">");
lv_obj_add_flag( ui_dayu, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_dayu, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dayu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dayu, &ui_font_MiSansM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time = lv_obj_create(ui_StepPannel);
lv_obj_set_width( ui_Time, 320);
lv_obj_set_height( ui_Time, 40);
lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Time, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_Time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Time, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Time, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Time, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dianchi1 = lv_label_create(ui_Time);
lv_obj_set_width( ui_dianchi1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dianchi1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dianchi1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_dianchi1,"日期和时间");
lv_obj_set_style_text_font(ui_dianchi1, &ui_font_MiSansM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dayu1 = lv_label_create(ui_Time);
lv_obj_set_width( ui_dayu1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dayu1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dayu1, 0 );
lv_obj_set_y( ui_dayu1, 3 );
lv_obj_set_align( ui_dayu1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_dayu1,">");
lv_obj_add_flag( ui_dayu1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_dayu1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dayu1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dayu1, &ui_font_MiSansM, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeImg, ui_event_HomeImg, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settingHeader, ui_event_settingHeader, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Bat, ui_event_Bat, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Time, ui_event_Time, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);

}
